export * from './sections/SectionProjects'
export * from './sections/TestimonialsSection'
export { HeroSection } from './sections/HeroSection'
export { default as ProcessSection } from './sections/processSection'
export { default as SolutionsSection } from './sections/solutionsSection'
