export * from './sections/SectionProjects'
export { HeroSection } from './sections/HeroSection'
export { default as ProcessSection } from './sections/processSection'
export { default as SolutionsSection } from './sections/solutionsSection'
export { default as PartnersSection } from './sections/partnersSection'