export * from './sections/ProjectsSection'
export * from './sections/TestimonialsSection'
export { HeroSection } from './sections/HeroSection'
export { default as ProcessSection } from './sections/processSection'
export { default as SolutionsSection } from './sections/solutionsSection'
export { default as PartnersSection } from './sections/PartnersSection'
export { default as CasesSection } from './sections/CasesSection'
